<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\JudicialOfficerPosting;
use App\JudicialOfficer;
use App\Zone;
use App\Subdivision;

use DB;
use Carbon\Carbon;

require_once base_path().'/vendor/autoload.php';


class ZoneOfConsiderationController extends Controller
{
    
    public function index()
    {
        return view('appointments.zone_of_consideration');
    }

    // Showing search result in datatable to prepare zone of consideration list
    public function get_zone_of_consideration(Request $request){
        $this->validate ( $request, [ 
            'zone' => 'required|integer|max:9999|exists:zones,id',
            'cadre' => 'required|integer|exists:ranks,id',
            'date_upto' => 'required|date',
            'year' => 'required|integer|max:15|min:0|required',
            'month' => 'required|integer|max:12|min:0|required',
            'day' => 'required|integer|max:30|min:0|required',            
        ]);
        
        $zone = $request->input('zone');
        $cadre = $request->input('cadre');
        $year = $request->input('year');
        $month = $request->input('month');
        $day = $request->input('day');
        $date_upto = date('Y-m-d', strtotime($request->input('date_upto')));
       

        // search_for_zone_of_consideration function is defined under the Controller class to make it available for other modules
        $record = Controller::search_for_zone_of_consideration($zone,$cadre,$year,$month,$day,$date_upto);

        echo json_encode($record);        

    }


    // Generate PDF of search result of zone of consideration list
    public function download_zone_of_consideration($zone,$cadre,$year,$month,$day,$date_upto){ 
        // search_for_zone_of_consideration function is defined under the Controller class to make it available for other modules
        $record = Controller::search_for_zone_of_consideration($zone,$cadre,$year,$month,$day,$date_upto);

        $content = "
                        <style>
                            table {
                                font-family: Arial, Helvetica, sans-serif;
                                border-collapse: collapse;
                                width: 100%;
                            }
                            
                            table td, table th {
                                border: 1px solid #ddd;
                                padding: 8px;
                            }
                            
                            table tr:nth-child(even){background-color: #f2f2f2;}
                            
                            table tr:hover {background-color: #ddd;}
                            
                            table th {
                                padding-top: 12px;
                                padding-bottom: 12px;
                                text-align: left;
                                background-color: black;
                                color: white;
                            }
                        </style>
                    ";

        $content.= '<table class="table1 table-striped table-bordered" id="show_cadrewise_zonewise_table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>OFFICER\'S NAME</th>                        
                                <th>POSTING HISTORY<br/>DURING THIS PERIOD</th>
                                <th>LAST CONTINUOUS POSTING<br/>IN THIS ZONE</th>
                                <th>DATE OF RETIREMENT</th>
                            </tr>
                        </thead>
                        <tbody>
                    ';
                    
        foreach($record as $key=>$val){
            $content.= "<tr>
                            <td>".(++$key)."</td>
                            <td>".$val['officer_name']."<br/>(".$val['jo_code'].")</td>
                            <td>".$val['posting_history']."</td>
                            <td>".$val['continuous_service_period']."<br/>SINCE ".$val['from_date']."</td>
                            <td>".$val['retirement_date']."</td>
                        </tr>";
        }

        $content.="</tbody></table>"; 

        

        $mpdf = new \Mpdf\Mpdf(['orientation' => 'L']);

        $mpdf->SetHTMLFooter('<hr>Report Generated by the IIMS - Calcutta High Court on '.Carbon::now()->format('d-m-Y').'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{PAGENO}');

echo $content;exit;
        $mpdf->WriteHTML($content);
        $mpdf->Output('zone_of_consideration_list.pdf','D');
        
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
